package com.bloodbank.common.enums;

public enum EventType {
    HOSPITAL_REGISTERED, HOSPITAL_DECIDED, DONATION_RECORDED, SCREENING_FAILED,
    DONATION_PASSED, REQUEST_CREATED, EMERGENCY_REQUEST, REQUEST_DECIDED,
    BLOOD_ISSUED, LOW_STOCK, UNIT_NEAR_EXPIRY, DONOR_ELIGIBLE_AGAIN
}